Allow spend tweaked pubKey
bitmask-stack/bitmask-core pull request #125
Opened 2022-12-24 17:16 UTC by crisdut

2022-12-24 22:49 UTC, cryptoquick requested changes
Wow, this looks pretty good. Just going to ask for one stylistic change. Also, can you modify the asset test to test multiple transfers?

2022-12-24 22:49 UTC, cryptoquick commented on src/bin/bitmaskd.rs
> -    let (consignment, psbt, disclosure, _, previous_utxo, _) = transfer_assets(
Please use destructuring assignment, similar to this:
https://github.com/diba-io/bitmask-core/blob/42dc3fad86c8a2b0a8d290950744fb10c07742b0/src/lib.rs#L570-L575

2022-12-28 17:02 UTC, crisdut commented
Hi,

I finished the implementation to support multiple-asset transfers.

**4 - Transfer Many Assets**
- One asset to one beneficiary
- One asset to many beneficiaries
- Many assets to one beneficiary 
- Many assets to many beneficiaries

To avoid break changes, I created new methods to help us test and approve this PR.

Also, I created a new endpoint in bitmaskd daemon to test it.

**How this works**

For now, I have created a new request to support this feature; see bellow:

```
{
    "descriptor_xpub": "tr(..)",                    // RGB Descriptor
    "transfers": [
        {
            "asset_utxo": {
                "outpoint": "74..17:1",             // Anchored UTXO
                "terminal_derivation": "/0/0",      // Descriptor Terminal Derivation
                "commitment": ""                    // TapTweak (Optional)
            },
            "asset_amount": 1000,                   // Total Asset Amount
            "change_utxo": "6e..eb5:1",             // Change UTXO for RGB
            "beneficiaries": [                      // List of Blinded Utxo + Amount
                "10@txob1..rt",
                "20@txob1..ld"
            ],
            "asset_contract": "rgbc1..65x"          // RGB Contract
        }
    ]
}
```

**Limitations**

Today the multiple asset UTXO needs to derive from the same descriptor.

I running on regtest, that's works.

2022-12-29 01:27 UTC, cryptoquick requested changes
I'm not worried about breaking changes, be sure to replace the old functionality with the new functionality, because the old functionality was essentially broken. Please get rid of the "transfers" plural endpoint, and v2 stuff. I don't want to maintain code that's already broken, does that make sense?

2022-12-29 01:36 UTC, crisdut commented
> I'm not worried about breaking changes, be sure to replace the old functionality with the new functionality, because the old functionality was essentially broken. Please get rid of the "transfers" plural endpoint, and v2 stuff. I don't want to maintain code that's already broken, does that make sense?

Sure, I maintained the old version to help us mapping the changes in other projects. So I will make a new commit to remove all the old code.

2022-12-29 19:01 UTC, josediegorobles approved these changes
Great work and changes, you have my ACK.

2022-12-31 05:55 UTC, closed without merging