Fix asset tests
bitmask-stack/bitmask-core pull request #141
Opened 2023-01-18 22:29 UTC by crisdut

I exposed state transfer, because the state transfer consignment is necessary to `accept_asset` step.

2023-01-18 23:16 UTC, cryptoquick approved these changes
ACK, LGTM... Though, can you explain to me what the difference is between a consignment and a state transfer? A state transfer is just a portion of the consignment, correct?

2023-01-18 23:33 UTC, cryptoquick commented
Nevermind, @crisdut, I just read your comment [here](https://github.com/diba-io/bitmask-core/pull/137#discussion_r1073893315), that explanation is sufficient, I think.

2023-01-18 23:44 UTC, crisdut commented
> ACK, LGTM... Though, can you explain to me what the difference is between a consignment and a state transfer? A state transfer is just a portion of the consignment, correct?

Yes, Sure

There is no big difference between the two, just that the state transfer has the current state of the contract plus the state transition data. The `state transfer`  is the final result of the rgb-cli transfer finalize operation.

2023-01-19 00:09 UTC, cryptoquick requested changes
Can you add a few comments that explains what just explained in the code for me, @crisdut ?

2023-01-19 08:50 UTC, josediegorobles approved these changes
LGTM

2023-01-19 09:49 UTC, cryptoquick approved these changes
Thanks for adding the comment, @crisdut! LGTM. Merging.

2023-01-19 09:49 UTC, merged