Use a database and JSON file for persistent, multi-day, live metrics.
bitmask-stack/bitmask-core pull request #440
Opened 2023-12-18 00:05 UTC by cryptoquick

This should be a superior approach that addresses a concern @crisdut raised about using a Lazy RwLock and also should lessen the burden on the server.

Supersedes #438

2023-12-18 10:44 UTC, josediegorobles commented
Lots of tests are failing

2023-12-18 14:05 UTC, crisdut commented
> Lots of tests are failing

I will check this. The error being described is related to file manipulation.

2023-12-18 15:50 UTC, crisdut requested changes

2023-12-18 15:50 UTC, crisdut commented on src/carbonado/metrics.rs
> +        serde_json::from_str(&fs::read_to_string(format!("{dir}/metrics.json")).await?)?;
When we run automated tests, no integration test initializes these files, which ends up causing the error.

Could we add a check here to see if the file exists?

2023-12-18 20:15 UTC, cryptoquick commented
@crisdut Can you check if bitmaskd isn't being instantiated in time for it to ensure the directory is initialized for backend integration tests?

2023-12-18 21:13 UTC, oacdutra commented
> Can you check if bitmaskd isn't being instantiated in time for it to ensure the directory is initialized for backend integration tests?

We instance `bitmaskd` only for wasm32 tests. For integration tests, we call functions directly.

We need a verification like this:

```rust
    let dir = env::var("CARBONADO_DIR").unwrap_or("/tmp/bitmaskd/carbonado".to_owned());
    if !Path::new(&format!("{dir}/metrics.json")).exists()
        || !Path::new(&format!("{dir}/metrics.csv")).exists()
    {
        init(Path::new(&dir)).await?;
    }
```

2023-12-19 00:25 UTC, crisdut approved these changes

2023-12-20 05:20 UTC, josediegorobles approved these changes
ACK

2023-12-20 05:23 UTC, merged