Rgb core ht api changes with modified transfer
bitmask-stack/bitmask-core pull request #72
Opened 2022-08-27 18:16 UTC by josediegorobles

2022-09-20 01:02 UTC, cryptoquick commented
I'll admit, I actually don't understand what key tweaking is for, or where it's used in RGB...

2022-09-20 11:42 UTC, josediegorobles commented
Sorry, i had to explain this:

The idea was follow same path that previous bitmask-extension:

1) Method in web.rs that is going to be executed in the extension/web where BDK forms a base PSBT ready for sign but without information about rgb assets

2) Method in lib that lambda is going to use for rgb-izing the PSBT: that was what the rgb-node does and now must be this rgb_tweaking method

3) Method in web.rs to sign the psbt that the lambda returns and send to the network.

We must have 1 and 3 in lib.rs too, so current send_assets calls 1,2,3 consecutively with essentially the same code and results that current send_assets.

I'm explaining well?

2022-09-21 00:44 UTC, cryptoquick requested changes
I still can't say I understand what this is for or why things are moved around. Can you explain more about what this supposed to do?

Also, can you add to the test for this? Maybe seeing it used will give me a better idea.

2022-09-21 00:44 UTC, cryptoquick commented on src/operations/rgb/send_tokens.rs
> -    let txid = tx.txid().to_string();
This line got lost

2022-09-21 00:44 UTC, cryptoquick commented on src/operations/rgb/send_tokens.rs
> -    // rgb-node -> cli/command -> TransferCommand::Combine
Why were these comments removed?

2022-09-21 07:04 UTC, josediegorobles commented
Yeah, this pr needs a good update

2022-09-22 11:00 UTC, josediegorobles commented
@cryptoquick I think I start with a too premature version this PR and is too messy, so I'm gonna start again is gonna be better and faster. I create another PR: https://github.com/diba-io/bitmask-core/pull/83 I hope that I can clarify intention and make a good start before I have to cut work, anyway we can discuss there the PR.

2022-09-22 11:00 UTC, closed without merging